OBJDIR := obj
LIBDIR := lib
INCDIR := inc

CC = gcc
CCFLAGS = -Werror -Wall -std=c11
AR = ar
ARFLAGS =
LD = gcc
LDFLAGS = -Werror -Wall -std=c11
MAKE = mingw32-make
MAKEFLAGS =

CD = cd
RM = del /F /Q
MKDIR = mkdir
